public class Addition {
    public static Integer add(Integer num1,Integer num2) {
        //method for addition
        Integer sum;
        sum=num1+num2;
        System.debug('Addition of '+num1+' and '+num2+' is '+sum);

     /*  for(integer i=0;i<5;i++)
       {
        Contact con=new Contact(lastName='LN'+i);
        //con.accountId='0015g0000150HO2AAM';
       // con.amount__c=1000;
        insert con;
       }
       for(integer i=0;i<2;i++)
       {
        Contact con=new Contact(lastName='LN'+i);
        //con.accountId='0015g0000150HO2AAM';
       // con.amount__c=1000;
        insert con;
       }*/
       //comment1
       return sum;
    }
}